spring:
  application:
    name: f1-api-server

  rsocket:
    server:
      transport: tcp
      port: 7000

  r2dbc:
    url: "r2dbc:h2:file:///./data/f1db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1"
    username: test
    password: test

  sql:
    init:
      mode: always
      encoding: UTF-8
