MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Lewis Hamilton', 'Mercedes', 44);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('George Russell', 'Mercedes', 63);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Max Verstappen', 'Red Bull', 1);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Sergio Perez', 'Red Bull', 11);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Charles Leclerc', 'Ferrari', 16);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Carlos Sainz', 'Ferrari', 55);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Lando Norris', 'McLaren', 4);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Oscar Piastri', 'McLaren', 81);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Fernando Alonso', 'Aston Martin', 14);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Lance Stroll', 'Aston Martin', 18);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Valtteri Bottas', 'Alfa Romeo', 77);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Zhou Guanyu', 'Alfa Romeo', 24);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Pierre Gasly', 'Alpine', 10);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Esteban Ocon', 'Alpine', 31);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Yuki Tsunoda', 'AlphaTauri', 22);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Nyck de Vries', 'AlphaTauri', 21);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Kevin Magnussen', 'Haas', 20);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Nico Hulkenberg', 'Haas', 27);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Logan Sargeant', 'Williams', 2);
MERGE INTO drivers (name, team, number) KEY (name) VALUES ('Alexander Albon', 'Williams', 23);
