spring:
  datasource:
    url: jdbc:postgresql://postgres-drivers:5432/drivers_db
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  sql:
    init:
      mode: always

server:
  port: 8081
