spring:
  datasource:
    url: jdbc:postgresql://postgres-races:5432/races_db
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    open-in-view: false

  sql:
    init:
      mode: always

server:
  port: 8083
